# Generated by Django 3.2.12 on 2022-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='duck.jpeg', upload_to='avatar/%Y/%m/%d'),
        ),
    ]
